const APP_KEY="thaiListeningClassroomV3";
const DB_VERSION=3;
const state={minimal:[],tones:[],faq:[],audio:{},voices:[],selectedVoiceURI:"",minimalFilter:"all",toneFilter:"all",currentStudentId:null,db:null};

document.addEventListener("DOMContentLoaded",init);
async function init(){setupNav();state.db=loadDB();await Promise.all([loadData(),setupVoices()]);setupEvents();renderAll();}

function blankDB(){return{version:DB_VERSION,students:[],records:[],sessions:[],settings:{createdAt:new Date().toISOString()}};}
function loadDB(){try{const raw=localStorage.getItem(APP_KEY);const db=raw?JSON.parse(raw):blankDB();if(!Array.isArray(db.students)||!Array.isArray(db.records)||!Array.isArray(db.sessions))throw new Error("invalid");state.currentStudentId=sessionStorage.getItem(`${APP_KEY}:current`)||null;return db;}catch{return blankDB();}}
function saveDB(){localStorage.setItem(APP_KEY,JSON.stringify(state.db));}
function currentStudent(){return state.db.students.find(s=>s.id===state.currentStudentId)||null;}
function uid(prefix){return`${prefix}_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;}

function setupNav(){const b=document.querySelector("#menuBtn"),l=document.querySelector("#navLinks");b.addEventListener("click",()=>{const open=l.classList.toggle("open");b.setAttribute("aria-expanded",String(open));});l.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{l.classList.remove("open");b.setAttribute("aria-expanded","false");}));}
async function loadData(){const [m,t,f,a]=await Promise.all([fetch("data/minimalPairs.json"),fetch("data/tonePairs.json"),fetch("data/faq.json"),fetch("data/audio-manifest.json").catch(()=>null)]);state.minimal=await m.json();state.tones=await t.json();state.faq=await f.json();state.audio=a&&a.ok?await a.json():{};fillSelect("#minimalFilter",state.minimal);fillSelect("#toneFilter",state.tones);updateAudioSourceStatus();}
async function setupVoices(){const s=document.querySelector("#voiceSelect");const load=()=>{state.voices=speechSynthesis?.getVoices?.()||[];const thai=state.voices.filter(v=>v.lang.toLowerCase().startsWith("th"));s.innerHTML="";if(!thai.length){s.innerHTML='<option value="">未偵測到泰語語音</option>';state.selectedVoiceURI="";return;}thai.sort((a,b)=>(Number(b.localService)-Number(a.localService))||a.name.localeCompare(b.name));thai.forEach(v=>{const o=document.createElement("option");o.value=v.voiceURI;o.textContent=`${v.name} · ${v.lang}${v.localService?" · 裝置內建":""}`;s.appendChild(o);});state.selectedVoiceURI=thai[0].voiceURI;s.value=state.selectedVoiceURI;};if(!window.speechSynthesis){s.innerHTML='<option value="">瀏覽器不支援語音</option>';return;}load();speechSynthesis.addEventListener?.("voiceschanged",load,{once:true});setTimeout(load,300);}
function updateAudioSourceStatus(){const verified=Object.values(state.audio).filter(Boolean).length;document.querySelector("#audioSourceStatus").textContent=verified?`已連接 ${verified} 題真人審核音檔；其餘使用泰語 TTS`:`目前使用泰語 TTS 備援；加入真人錄音後會自動優先播放`;}

function setupEvents(){
  document.querySelector("#voiceSelect").addEventListener("change",e=>state.selectedVoiceURI=e.target.value);
  document.querySelector("#loginBtn").addEventListener("click",loginStudent);document.querySelector("#participantId").addEventListener("keydown",e=>{if(e.key==="Enter")loginStudent();});
  document.querySelector("#logoutBtn").addEventListener("click",logout);
  document.querySelector("#minimalFilter").addEventListener("change",e=>{state.minimalFilter=e.target.value;renderMinimal();});document.querySelector("#toneFilter").addEventListener("change",e=>{state.toneFilter=e.target.value;renderTones();});
  document.querySelector("#minimalShuffle").addEventListener("click",()=>{state.minimal=shuffle([...state.minimal]);renderMinimal();});document.querySelector("#toneShuffle").addEventListener("click",()=>{state.tones=shuffle([...state.tones]);renderTones();});
  document.querySelector("#exportCsvBtn").addEventListener("click",exportCSV);document.querySelector("#backupBtn").addEventListener("click",backupAll);document.querySelector("#restoreInput").addEventListener("change",restoreAll);document.querySelector("#resetBtn").addEventListener("click",resetCurrentStudent);
}
function loginStudent(){const participantId=normalizeCode(document.querySelector("#participantId").value);if(!/^[A-Z0-9_-]{2,12}$/.test(participantId))return setStatus("請輸入 2–12 位英文字母或數字，例如 A01。",true);let student=state.db.students.find(s=>normalizeCode(s.participantId||s.code||s.id)===participantId);const now=new Date().toISOString();if(!student){student={id:uid("stu"),participantId,name:participantId,code:participantId,className:"",createdAt:now,lastLoginAt:now,loginCount:0};state.db.students.push(student);}student.participantId=participantId;student.name=participantId;student.code=participantId;student.lastLoginAt=now;student.loginCount=(student.loginCount||0)+1;state.db.sessions.push({id:uid("ses"),studentId:student.id,type:"login",at:now});state.db.sessions=state.db.sessions.slice(-1000);saveDB();setCurrentStudent(student.id);document.querySelector("#participantId").value="";setStatus(`受試者 ${participantId} 已登入。`);renderAll();}
function logout(){const s=currentStudent();if(s){state.db.sessions.push({id:uid("ses"),studentId:s.id,type:"logout",at:new Date().toISOString()});saveDB();}state.currentStudentId=null;sessionStorage.removeItem(`${APP_KEY}:current`);setStatus("已安全登出。");renderAll();}
function setCurrentStudent(id){state.currentStudentId=id;sessionStorage.setItem(`${APP_KEY}:current`,id);}
function normalizeCode(v){return String(v||"").trim().replace(/\s+/g,"").toUpperCase();}function setStatus(msg,error=false){const e=document.querySelector("#loginStatus");e.textContent=msg;e.classList.toggle("error",error);}

function renderAll(){renderProfile();renderMinimal();renderTones();renderFAQ();renderRecords();}
function studentRecords(){const s=currentStudent();return s?state.db.records.filter(r=>r.studentId===s.id):[];}
function renderProfile(){const s=currentStudent(),box=document.querySelector("#currentProfile"),nav=document.querySelector("#navStudent"),logoutBtn=document.querySelector("#logoutBtn");if(!s){box.innerHTML='<div class="profile-name">尚未登入</div><p class="profile-meta">輸入受試者編號後，系統才會保存作答紀錄。</p>';nav.textContent="尚未登入";logoutBtn.hidden=true;return;}const participantId=s.participantId||s.code||s.name,rs=studentRecords(),correct=rs.filter(r=>r.isCorrect).length;box.innerHTML=`<div class="profile-name">${esc(participantId)}</div><p class="profile-meta">受試者編號</p><div class="profile-stats"><div><span>已練習</span><strong>${rs.length}</strong></div><div><span>正確率</span><strong>${rs.length?Math.round(correct/rs.length*100):0}%</strong></div></div><small>上次登入：${formatDate(s.lastLoginAt)}</small>`;nav.textContent=participantId;logoutBtn.hidden=false;}
function fillSelect(sel,data){const s=document.querySelector(sel);s.innerHTML='<option value="all">全部題組</option>';[...new Set(data.map(i=>i.category))].forEach(c=>s.insertAdjacentHTML("beforeend",`<option value="${esc(c)}">${esc(categoryLabel(c))}</option>`));}
function categoryLabel(c){return{"บ_vs_ป":"บ vs ป","ด_vs_ต":"ด vs ต","ง_vs_น":"ง vs น","ร_vs_ล":"ร vs ล","low_vs_falling":"低聲 vs 降聲","mid_vs_rising":"中聲 vs 升聲","low_vs_rising":"低聲 vs 升聲","falling_vs_rising":"降聲 vs 升聲",all:"全部題組"}[c]||c;}
function filtered(d,c){return c==="all"?d:d.filter(i=>i.category===c);}function renderMinimal(){renderQuestions("#minimalQuestions","#minimalCount",filtered(state.minimal,state.minimalFilter));}function renderTones(){renderQuestions("#toneQuestions","#toneCount",filtered(state.tones,state.toneFilter));}
function renderQuestions(listSel,countSel,data){document.querySelector(countSel).textContent=`${data.length} 題`;document.querySelector(listSel).innerHTML=data.map((i,n)=>qHTML(i,n)).join("");attach(listSel);}
function qHTML(i,n){const con=i.toneContour?`<span class="contour">${toneSymbol(i.toneContour)}</span>`:"",ai=i.wordA.toneName||i.wordA.feature||"",bi=i.wordB.toneName||i.wordB.feature||"",hasAudio=Boolean(state.audio[i.id]||i.audioUrl);return `<article class="question-card" data-id="${esc(i.id)}" data-answer="${esc(i.correctAnswer)}" data-speak="${esc(i.speakText||i.correctAnswer)}" data-category="${esc(i.category)}" data-focus="${esc(i.focus)}" data-audio="${esc(state.audio[i.id]||i.audioUrl||"")}"><div class="question-number">${String(n+1).padStart(2,"0")}</div><div class="meta">${esc(categoryLabel(i.category))} · ${esc(i.focus)}</div><div class="question-title">請聽語音，選出你聽到的詞 ${con}</div><div class="pair-preview"><div class="word-chip">${esc(i.wordA.thai)}<small>${esc(ai)}</small></div><div class="word-chip">${esc(i.wordB.thai)}<small>${esc(bi)}</small></div></div><div class="audio-row"><button class="btn primary small play-question">▶ 播放</button><button class="btn ghost small play-question-slow">慢速</button><span class="audio-badge">${hasAudio?"真人審核音檔":"泰語 TTS"}</span><span class="audio-status" aria-live="polite">準備播放</span></div><div class="option-row"><button class="option-btn" data-choice="${esc(i.wordA.thai)}">A. <span>${esc(i.wordA.thai)}</span></button><button class="option-btn" data-choice="${esc(i.wordB.thai)}">B. <span>${esc(i.wordB.thai)}</span></button></div><div class="feedback"></div><template class="explain">${esc(i.explanation)}</template></article>`;}
function attach(sel){const root=document.querySelector(sel);root.querySelectorAll(".play-question").forEach(b=>b.addEventListener("click",e=>playQuestion(e,false)));root.querySelectorAll(".play-question-slow").forEach(b=>b.addEventListener("click",e=>playQuestion(e,true)));root.querySelectorAll(".option-btn").forEach(b=>b.addEventListener("click",check));}
async function playQuestion(e,slow){const c=e.currentTarget.closest(".question-card"),st=c.querySelector(".audio-status"),rate=slow ? 0.68 : Number(document.querySelector("#playbackRate").value||0.82);await playAudio({url:c.dataset.audio,text:c.dataset.speak,rate,onStart:()=>st.textContent="正在播放…",onEnd:()=>st.textContent="播放完成"});}
async function playAudio({url,text,rate,onStart,onEnd}){speechSynthesis?.cancel();if(url){const audio=new Audio(url);audio.playbackRate=rate;audio.onplay=onStart;audio.onended=onEnd;audio.onerror=()=>speakTTS(text,rate,onStart,onEnd);try{await audio.play();return;}catch{/* fallback below */}}speakTTS(text,rate,onStart,onEnd);}
function speakTTS(text,rate,onStart,onEnd){if(!window.speechSynthesis)return alert("此瀏覽器不支援語音播放，請改用最新版 Chrome、Edge 或 Safari。");const u=new SpeechSynthesisUtterance(text);u.lang="th-TH";u.rate=rate;u.pitch=1;u.volume=1;const voice=state.voices.find(v=>v.voiceURI===state.selectedVoiceURI);if(voice)u.voice=voice;u.onstart=onStart;u.onend=onEnd;u.onerror=()=>alert("泰語語音播放失敗，請確認裝置已安裝 Thai 語音。");speechSynthesis.speak(u);}
function check(e){const b=e.currentTarget,c=b.closest(".question-card"),answer=c.dataset.answer,choice=b.dataset.choice,ok=choice===answer,fb=c.querySelector(".feedback"),ex=c.querySelector(".explain").innerHTML;c.querySelectorAll(".option-btn").forEach(x=>{x.disabled=true;if(x.dataset.choice===answer)x.classList.add("correct");if(x.dataset.choice===choice&&!ok)x.classList.add("incorrect");});fb.className=`feedback show ${ok?"ok":"no"}`;fb.innerHTML=`<strong>${ok?"答對了！":"再聽一次會更清楚。"}</strong><br>正確答案：<strong>${esc(answer)}</strong><br>${ex}<br><button class="btn small primary play-answer">播放正確單字</button>`;fb.querySelector(".play-answer").addEventListener("click",()=>playAudio({url:c.dataset.audio,text:answer,rate:Number(document.querySelector("#playbackRate").value||.82)}));addRecord({questionId:c.dataset.id,category:categoryLabel(c.dataset.category),focus:c.dataset.focus,word:c.dataset.speak,selected:choice,correctAnswer:answer,isCorrect:ok,audioSource:c.dataset.audio?"verified":"tts"});}
function addRecord(rec){const s=currentStudent();if(!s){setStatus("這次作答未保存；請先登入學生帳號。",true);return;}state.db.records.unshift({...rec,id:uid("rec"),studentId:s.id,at:new Date().toISOString()});state.db.records=state.db.records.slice(0,5000);saveDB();renderProfile();renderRecords();}

function renderRecords(){const s=currentStudent(),records=studentRecords(),summary=document.querySelector("#summaryCards");if(!s){summary.innerHTML=summaryHTML(0,0,0,0);document.querySelector("#categoryReport").innerHTML='<p class="empty">登入後顯示題組表現</p>';document.querySelector("#recordList").innerHTML='<p class="empty">尚未登入學生帳號</p>';return;}const correct=records.filter(r=>r.isCorrect).length,rate=records.length?Math.round(correct/records.length*100):0,cats=groupCategories(records),weak=Object.values(cats).sort((a,b)=>a.rate-b.rate)[0];summary.innerHTML=summaryHTML(records.length,correct,rate,s.loginCount||0);document.querySelector("#categoryReport").innerHTML=Object.values(cats).length?Object.values(cats).sort((a,b)=>a.rate-b.rate).map(c=>`<div class="report-row"><div class="report-row-head"><span>${esc(c.name)}</span><span>${c.correct}/${c.total} · ${c.rate}%</span></div><div class="bar"><i style="width:${c.rate}%"></i></div></div>`).join(""):'<p class="empty">完成第一題後，這裡會顯示強弱項。</p>';document.querySelector("#recordList").innerHTML=records.length?records.slice(0,30).map(r=>`<div class="record-item"><strong>${esc(r.word)}</strong> · ${esc(r.category)} · ${r.isCorrect?"正確":"錯誤"}<br><small>${formatDate(r.at)} · ${r.audioSource==="verified"?"真人音檔":"TTS"}</small></div>`).join(""):'<p class="empty">目前沒有作答紀錄。</p>';}
function summaryHTML(total,correct,rate,logins){return`<div class="summary-card"><span>總作答</span><strong>${total}</strong></div><div class="summary-card"><span>答對題數</span><strong>${correct}</strong></div><div class="summary-card"><span>正確率</span><strong>${rate}%</strong></div><div class="summary-card"><span>登入次數</span><strong>${logins}</strong></div>`;}
function groupCategories(records){return records.reduce((o,r)=>{o[r.category]??={name:r.category,total:0,correct:0,rate:0};o[r.category].total++;if(r.isCorrect)o[r.category].correct++;o[r.category].rate=Math.round(o[r.category].correct/o[r.category].total*100);return o;},{});}
function resetCurrentStudent(){const s=currentStudent();if(!s)return alert("請先輸入受試者編號。");const participantId=s.participantId||s.code||s.name;if(confirm(`確定清除受試者 ${participantId} 的所有作答紀錄嗎？編號與登入紀錄會保留。`)){state.db.records=state.db.records.filter(r=>r.studentId!==s.id);saveDB();renderAll();}}
function exportCSV(){const s=currentStudent();if(!s)return alert("請先輸入受試者編號。");const participantId=s.participantId||s.code||s.name;const rows=[["participant_id","time","question_id","category","focus","word","selected","answer","correct","audio_source"],...studentRecords().map(r=>[participantId,r.at,r.questionId,r.category,r.focus,r.word,r.selected,r.correctAnswer,r.isCorrect?"TRUE":"FALSE",r.audioSource])];download(`thai-records-${safeName(participantId)}.csv`,"\ufeff"+rows.map(row=>row.map(csvCell).join(",")).join("\n"),"text/csv;charset=utf-8");}
function backupAll(){download(`thai-classroom-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({...state.db,exportedAt:new Date().toISOString()},null,2),"application/json");}
async function restoreAll(e){const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.students)||!Array.isArray(data.records)||!Array.isArray(data.sessions))throw new Error();if(!confirm(`備份包含 ${data.students.length} 位學生、${data.records.length} 筆作答。確定取代目前資料嗎？`))return;state.db={...blankDB(),...data,version:DB_VERSION};state.currentStudentId=null;sessionStorage.removeItem(`${APP_KEY}:current`);saveDB();renderAll();setStatus("備份已成功還原。");}catch{alert("無法讀取這份備份，請確認它是由本平台匯出的 JSON 檔。教學紀錄未變更。");}finally{e.target.value="";}}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}function csvCell(v){return`"${String(v??"").replaceAll('"','""')}"`;}function safeName(v){return String(v).replace(/[^\p{L}\p{N}_-]+/gu,"-");}
function renderFAQ(){document.querySelector("#faqList").innerHTML=state.faq.map(i=>`<article class="faq-item"><button class="faq-q" aria-expanded="false">${esc(i.question)}</button><div class="faq-a">${i.answer}</div></article>`).join("");document.querySelectorAll(".faq-q").forEach(b=>b.addEventListener("click",()=>{const open=b.closest(".faq-item").classList.toggle("open");b.setAttribute("aria-expanded",String(open));}));}
function formatDate(iso){if(!iso)return"—";return new Intl.DateTimeFormat("zh-TW",{dateStyle:"short",timeStyle:"short"}).format(new Date(iso));}function toneSymbol(t){return{mid:"─",low:"▁",falling:"↘",rising:"↗"}[t]||t;}function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
